# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

# http://docs.travis-ci.com/user/gui-and-headless-browsers
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 # start xvbfb for e2e tests with screen resolution 1280x1024x16
 - "export DISPLAY=:99.0"
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
 # give xvfb some time to start
 - sleep 3
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 - google-chrome --version

install:
  - npm install

before_script:
  - npm run lint

# http://docs.travis-ci.com/user/pull-requests/
script:
  - npm test
